name: e_commerce_v2
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  dots_indicator: ^4.0.1
  cached_network_image: ^3.4.1
  icons_plus:

  # State Management
  flutter_bloc:

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.5.1

  # Networking
  dio: ^5.9.0
  retrofit: ^4.7.2   # متوافق مع generator الجديد
  json_annotation: ^4.9.0
  logger: ^2.6.0     # للـ logging

  # Native Splash + Icons
  flutter_native_splash:
  icons_launcher:
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Quality
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  retrofit_generator: ^10.0.1   # متوافق مع retrofit ^4.7.2


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svgs/
